import { Router } from "express";
import commentRouter from "./commentRouter.js";
import postContoller from "./../controllers/postController.js";
import isAuthor from "../lib/isAuthor.js";
import isPostAuthor from "../lib/isPostAuthor.js";
const postRouter = Router();
postRouter.get("/", postContoller.get_all);
postRouter.get("/:postId", postContoller.get_post);
postRouter.post("/", isAuthor, postContoller.create_one);
postRouter.put("/:postId", isAuthor, isPostAuthor, postContoller.update);
postRouter.delete("/:postId", isAuthor, isPostAuthor, postContoller.delete);
postRouter.use("/:postId/comments", commentRouter);
export default postRouter;
